#!/bin/bash
sudo apt-get install build-essential
sleep 2
wget -qO- https://raw.githubusercontent.com/creationix/nvm/v0.31.0/install.sh | bash
sleep 2
reset
source ~/.nvm/nvm.sh
nvm install v5.6.0
nvm use v5.6.0
reset
source ~/.bashrc
sleep 2
npm i
reset
npm run build
sleep 2
npm start
